# Generated by Django 3.0 on 2022-05-16 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 23, 48, 724448))),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_name', models.CharField(blank=True, max_length=128, null=True)),
                ('venue', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('reg_end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('reg_fee', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'Event',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 23, 48, 724448))),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], max_length=10)),
                ('attandance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=14)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=140)),
                ('phone_code', models.CharField(default='91', max_length=30)),
                ('address', models.TextField()),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.District')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'verbose_name': 'Event Ticket',
                'verbose_name_plural': 'Event Tickets',
                'db_table': 'Event_Ticket',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 23, 48, 724448))),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mobile_image', versatileimagefield.fields.VersatileImageField(upload_to='images/event/banner/mobile/', verbose_name='mobile_image')),
                ('web_image', versatileimagefield.fields.VersatileImageField(upload_to='images/event/banner/web/', verbose_name='web_image')),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'Banner',
                'ordering': ('-date_added',),
            },
        ),
    ]
