# Generated by Django 3.0 on 2022-05-17 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220516_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 17, 36, 31, 973548)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 17, 36, 31, 973548)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='attandance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending')], max_length=14),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 17, 36, 31, 973548)),
        ),
    ]
